const $=s=>document.querySelector(s);
let levels=[],books=[],chosen=-1,current=null,entries=[],font=19,onlyFavorites=false,loadToken=0;
const colors=['#657d50','#247466','#b28445','#7b708e','#567c99','#995e55','#4d6572','#93662f'];
const readStore=k=>{try{return localStorage.getItem(k)}catch{return null}},writeStore=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const readJSON=(k,f)=>{try{return JSON.parse(readStore(k))||f}catch{return f}};
let favorites=new Set(readJSON('bookworms-favorites',[])),history=readJSON('bookworms-history',{}),night=readStore('bookworms-theme')==='dark';
const normalize=s=>s.toLowerCase().replace(/[\s·•・—:：]/g,'');
const flatten=n=>[n,...(n.children||[]).flatMap(flatten)];
function closeMenu(){$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}
$('#menu').onclick=()=>{let open=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open))};
function theme(){document.documentElement.dataset.theme=night?'dark':'light';$('#theme').textContent=night?'☀ 日间':'☾ 夜间';$('#theme').setAttribute('aria-pressed',String(night));writeStore('bookworms-theme',night?'dark':'light');styleContent()}
$('#theme').onclick=()=>{night=!night;theme()};
function styleContent(){const d=$('#page').contentDocument;if(!d?.body||$('#page').dataset.kind==='pdf')return;let style=d.getElementById('reading-preferences');if(!style){style=d.createElement('style');style.id='reading-preferences';d.head.append(style)}style.textContent=`html,body{background:${night?'#18251f':'#fffcf5'}!important;color:${night?'#dce5dc':'#242e2b'}!important}body,p,div,li{font-size:${font}px!important;line-height:1.9!important}${night?'p,div,span,h1,h2,h3{color:#dce5dc!important}a{color:#a3d7b6!important}':''}`}
function draw(){const q=normalize($('#search').value.trim());let shown=books.filter(b=>(chosen<0||b.level===chosen)&&(!onlyFavorites||favorites.has(b.id))&&flatten(b).some(n=>normalize(n.title).includes(q)));if($('#sort').value==='recent')shown.sort((a,b)=>(history[b.id]?.time||0)-(history[a.id]?.time||0));if($('#sort').value==='title')shown.sort((a,b)=>a.title.localeCompare(b.title,'zh-CN'));$('#books').replaceChildren();for(const b of shown){const a=document.createElement('a');a.className='card';a.href=history[b.id]?.hash||'#book='+b.id;a.style.setProperty('--accent',colors[b.level%colors.length]);const s=document.createElement('small');s.textContent=levels[b.level].label+(favorites.has(b.id)?' · ★':'');const h=document.createElement('h3');h.textContent=b.title;const p=document.createElement('span');p.textContent=(history[b.id]?'继续阅读':'打开阅读')+' ↗'+(b.level===7?' · '+b.children.map(v=>v.title.replace('版','')).join(' / '):'');a.append(s,h,p);$('#books').append(a)}$('#count').textContent=`${shown.length} 个书目`;$('#empty').hidden=shown.length>0;$('#shelfTitle').textContent=onlyFavorites?'我的收藏':chosen<0?'全部读物':levels[chosen].label;document.querySelectorAll('#filters button').forEach((x,i)=>{x.classList.toggle('active',i-1===chosen);x.setAttribute('aria-pressed',String(i-1===chosen))});document.querySelectorAll('.tree-books a').forEach(a=>{a.hidden=!shown.some(b=>b.id===a.dataset.id)});document.querySelectorAll('#tree details').forEach(d=>{d.hidden=![...d.querySelectorAll('a')].some(a=>!a.hidden);if(q)d.open=true});$('#favorites').setAttribute('aria-pressed',String(onlyFavorites));$('#favorites').textContent=onlyFavorites?'★ 显示全部':'☆ 只看收藏'}
function savePosition(hash=location.hash){if(!current)return;history[current.id]={hash,time:Date.now()};writeStore('bookworms-history',JSON.stringify(history));writeStore('bookworms-last',hash);$('#resume').href=hash;$('#resume').hidden=false}
function star(){$('#bookmark').textContent=favorites.has(current?.id)?'★ 已收藏':'☆ 收藏本书';$('#bookmark').setAttribute('aria-pressed',String(favorites.has(current?.id)))}
$('#bookmark').onclick=()=>{if(!current)return;if(favorites.has(current.id))favorites.delete(current.id);else favorites.add(current.id);writeStore('bookworms-favorites',JSON.stringify([...favorites]));star();draw()};
$('#favorites').onclick=()=>{onlyFavorites=!onlyFavorites;draw()};$('#sort').onchange=draw;
function route(){setTools(false);const token=++loadToken,p=new URLSearchParams(location.hash.slice(1));current=books.find(b=>b.id===p.get('book'));document.body.classList.toggle('reading',!!current);if(!current)document.body.classList.remove('focus-reading');$('#home').hidden=!!current;$('#reader').hidden=!current;if(!current){document.title='书虫 · 双语阅读书房';$('#page').src='about:blank';draw();return}closeMenu();entries=current.level===7?current.children.flatMap(flatten):flatten(current);let i=Math.max(0,Math.min(entries.length-1,Math.floor(Number(p.get('chapter'))||0)));$('#bookTitle').textContent=current.title;document.title=current.title+' · 书虫双语书房';$('#breadcrumb').textContent=levels[current.level].label+' / '+current.title;$('#chapters').replaceChildren();entries.forEach((n,j)=>{$('#chapters').add(new Option((current.level!==7&&j===0?'封面 · ':'')+n.title,String(j)))});$('#chapters').value=i;$('#prev').disabled=i===0;$('#next').disabled=i===entries.length-1;$('#readStatus').textContent='正在打开：'+entries[i].title;const e=entries[i],isPDF=e.format==='pdf',frame=$('#page');frame.dataset.kind=isPDF?'pdf':'html';frame.setAttribute('sandbox',isPDF?'allow-same-origin allow-scripts allow-downloads allow-modals':'allow-same-origin');$('#smaller').hidden=$('#larger').hidden=isPDF;$('#position').textContent='';$('#original').href=e.href;$('#original').hidden=!isPDF;$('#readingHint').textContent=isPDF?'PDF 支持搜索、页码跳转和缩放。阅读页码保存在当前浏览器。':(current.note||'原文、译文和练习按原目录保留。')+' 章节位置保存在当前浏览器；图片页不受字号按钮影响。';let page=Math.max(1,parseInt(p.get('page'))||Number(readStore('pdf-page:'+e.href))||1);frame.onload=()=>onFrameLoad(token,e,i);$('#screenPrev').textContent=isPDF?'← 上一页':'← 上一屏';$('#screenNext').textContent=isPDF?'下一页 →':'下一屏 →';$('#screenPosition').textContent='';const sameDocument=!isPDF&&frame.src.split('#')[0]===new URL(e.href,location.href).href.split('#')[0]&&frame.contentDocument?.readyState==='complete';frame.src=isPDF?'vendor/pdfjs/web/viewer.html?file='+encodeURIComponent(new URL(e.href,location.href).pathname)+'#page='+page+'&zoom=page-width':e.href;if(sameDocument)requestAnimationFrame(()=>onFrameLoad(token,e,i));savePosition();star();document.querySelectorAll('.tree-books a').forEach(a=>{a.classList.toggle('active',a.dataset.id===current.id);if(a.dataset.id===current.id){a.hidden=false;a.closest('details').hidden=false;a.closest('details').open=true}})}
async function onFrameLoad(token,e,i){if(token!==loadToken||!current)return;const frame=$('#page'),d=frame.contentDocument;if(!d)return;if(e.format==='pdf'){try{const app=frame.contentWindow.PDFViewerApplication;if(!app)throw Error('阅读器初始化失败');await app.initializedPromise;if(token!==loadToken)return;const update=()=>{if(token!==loadToken||!current)return;const p=app.page||1;$('#readStatus').textContent='已打开 · '+e.title+' · PDF';$('#position').textContent=`第 ${p} / ${app.pagesCount} 页`;$('#screenPosition').textContent=`${p} / ${app.pagesCount}`;writeStore('pdf-page:'+e.href,String(p));const hash='#book='+current.id+'&chapter='+i+'&page='+p;window.history.replaceState(null,'',hash);savePosition(hash)};app.eventBus.on('pagesloaded',update);app.eventBus.on('pagechanging',update);if(app.pagesCount)update()}catch(err){$('#readStatus').textContent='PDF 加载失败，可点击“打开原文件”重试';console.error(err)}return}styleContent();installPaging(d,e,token);$('#readStatus').textContent='已打开 · '+(d.title||current.title);d.addEventListener('click',ev=>{const a=ev.target.closest('a[href]');if(!a)return;const u=new URL(a.getAttribute('href'),d.URL),base=new URL('content/',location.href);if(u.origin!==base.origin||!u.pathname.startsWith(base.pathname)){ev.preventDefault();return}const j=entries.findIndex(x=>new URL(x.href,location.href).href===u.href);if(j>=0){ev.preventDefault();go(j)}})}
function go(i){location.hash='book='+current.id+'&chapter='+i}
$('#chapters').onchange=e=>go(e.target.value);$('#prev').onclick=()=>go(Number($('#chapters').value)-1);$('#next').onclick=()=>go(Number($('#chapters').value)+1);
$('#larger').onclick=()=>{font=Math.min(32,font+2);writeStore('bookworms-font',String(font));styleContent()};$('#smaller').onclick=()=>{font=Math.max(14,font-2);writeStore('bookworms-font',String(font));styleContent()};
$('#search').oninput=()=>{if(current)location.hash='';draw()};window.onhashchange=route;
Promise.all(['catalog.json','classics.json','world770.json'].map(u=>fetch(u).then(r=>{if(!r.ok)throw Error('目录加载失败');return r.json()}))).then(([data,extra,world])=>{levels=[...data,extra,...world];books=levels.flatMap(l=>l.children);$('#total').textContent=books.length+' 个书目';$('#statTotal').textContent=books.length;$('#statWorld').textContent=world.reduce((n,l)=>n+l.children.length,0);[-1,...levels.keys()].forEach(i=>{const b=document.createElement('button');b.textContent=i<0?'全部':levels[i].label;b.onclick=()=>{chosen=i;draw()};$('#filters').append(b)});levels.forEach(l=>{const d=document.createElement('details'),s=document.createElement('summary'),list=document.createElement('div');s.textContent=l.label+' · '+l.children.length;list.className='tree-books';l.children.forEach(b=>{const a=document.createElement('a');a.href='#book='+b.id;a.dataset.id=b.id;a.textContent=b.title;list.append(a)});d.append(s,list);$('#tree').append(d)});const last=readStore('bookworms-last');if(last&&last.startsWith('#book=')){$('#resume').href=last;$('#resume').hidden=false}font=Math.min(32,Math.max(14,Number(readStore('bookworms-font'))||19));theme();draw();route()}).catch(e=>{$('#count').textContent='加载失败，请刷新重试';console.error(e)});

let scrollSaveTimer, pendingBottom=false;
$('#focus').onclick=()=>{setTools(false);const on=document.body.classList.toggle('focus-reading');$('#focus').textContent=on?'↙ 退出专注':'⛶ 专注阅读';setTimeout(updateScreenPosition,100)};
function updateScreenPosition(){const d=$('#page').contentDocument;if(!d||$('#page').dataset.kind==='pdf')return;const el=d.scrollingElement;if(!el)return;const h=el.clientHeight||$('#page').clientHeight;const step=Math.max(80,h-35),max=Math.max(0,el.scrollHeight-h),total=Math.ceil(max/step)+1;const index=el.scrollTop>=max-3?total:Math.round(el.scrollTop/step)+1;$('#screenPosition').textContent=`${Math.min(total,index)} / ${total} 屏`}
function turnScreen(direction){if(!current)return;const frame=$('#page');if(frame.dataset.kind==='pdf'){const a=frame.contentWindow.PDFViewerApplication;if(a?.pagesCount)a.page=Math.max(1,Math.min(a.pagesCount,a.page+direction));return}const d=frame.contentDocument,el=d?.scrollingElement;if(!el)return;const max=el.scrollHeight-el.clientHeight,step=Math.max(80,el.clientHeight-35);if(direction>0&&el.scrollTop>=max-3){if(Number($('#chapters').value)<entries.length-1)go(Number($('#chapters').value)+1)}else if(direction<0&&el.scrollTop<=2){if(Number($('#chapters').value)>0){pendingBottom=true;go(Number($('#chapters').value)-1)}}else{el.scrollTo({top:Math.max(0,Math.min(max,el.scrollTop+direction*step)),behavior:'smooth'})}}
$('#screenPrev').onclick=()=>turnScreen(-1);$('#screenNext').onclick=()=>turnScreen(1);
function pageKey(e){if(!current||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;let dir=0;if(['ArrowRight','PageDown',' '].includes(e.key))dir=e.shiftKey?-1:1;if(['ArrowLeft','PageUp'].includes(e.key))dir=-1;if(dir){e.preventDefault();turnScreen(dir)}}
document.addEventListener('keydown',pageKey);
function installPaging(d,entry,token){d._pagingAbort?.abort();const ctrl=new AbortController();d._pagingAbort=ctrl;d.addEventListener('keydown',pageKey,{signal:ctrl.signal});const el=d.scrollingElement,key='bookworms-scroll:'+entry.href;const savedValue=readStore(key),saved=Number(savedValue)||0;const restore=()=>{if(token!==loadToken)return;if(pendingBottom)el.scrollTop=el.scrollHeight;else if(savedValue!==null)el.scrollTop=saved;pendingBottom=false;updateScreenPosition()};requestAnimationFrame(restore);d.addEventListener('scroll',()=>{updateScreenPosition();clearTimeout(scrollSaveTimer);scrollSaveTimer=setTimeout(()=>{if(token===loadToken)writeStore(key,String(el.scrollTop))},150)},{passive:true,signal:ctrl.signal});for(const img of d.images)if(!img.complete)img.addEventListener('load',updateScreenPosition,{once:true,signal:ctrl.signal});let start=null;d.addEventListener('touchstart',ev=>{if(ev.touches.length===1)start={x:ev.touches[0].clientX,y:ev.touches[0].clientY}},{passive:true,signal:ctrl.signal});d.addEventListener('touchend',ev=>{if(!start||!ev.changedTouches.length)return;const dx=ev.changedTouches[0].clientX-start.x,dy=ev.changedTouches[0].clientY-start.y;start=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5&&!d.getSelection()?.toString())turnScreen(dx<0?1:-1)},{passive:true,signal:ctrl.signal})}
window.addEventListener('resize',updateScreenPosition);

function setTools(open){$('#readerTools').hidden=!open;$('#toolsToggle').setAttribute('aria-expanded',String(open));$('#toolsToggle').setAttribute('aria-label',open?'收起阅读工具':'展开阅读工具');$('#toolsToggle').textContent=open?'×':'⋯'}
$('#toolsToggle').onclick=()=>setTools($('#readerTools').hidden);
document.addEventListener('keydown',e=>{if(e.key==='Escape')setTools(false)});
$('#page').addEventListener('load',()=>{try{$('#page').contentDocument?.addEventListener('pointerdown',()=>setTools(false))}catch{}});
