const $=s=>document.querySelector(s);let levels=[],books=[],chosen=-1,current=null,entries=[],font=19;
const colors=['#657d50','#247466','#b28445','#7b708e','#567c99','#995e55','#4d6572'];
const readStore=k=>{try{return localStorage.getItem(k)}catch{return null}},writeStore=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const normalize=s=>s.toLowerCase().replace(/[\s·•・—:：]/g,'');
const flatten=n=>[n,...(n.children||[]).flatMap(flatten)];
function closeMenu(){$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}
$('#menu').onclick=()=>{let open=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open))};
function draw(){const q=normalize($('#search').value.trim());let shown=books.filter(b=>(chosen<0||b.level===chosen)&&flatten(b).some(n=>normalize(n.title).includes(q)));$('#books').replaceChildren();for(const b of shown){const a=document.createElement('a');a.className='card';a.href='#book='+b.id;a.style.setProperty('--accent',colors[b.level]);const s=document.createElement('small');s.textContent=levels[b.level].label;const h=document.createElement('h3');h.textContent=b.title;const p=document.createElement('span');p.textContent='打开阅读 ↗';a.append(s,h,p);$('#books').append(a)}$('#count').textContent=`${shown.length} 本读物`;$('#empty').hidden=shown.length>0;$('#shelfTitle').textContent=chosen<0?'全部读物':levels[chosen].label;document.querySelectorAll('#filters button').forEach((x,i)=>{x.classList.toggle('active',i-1===chosen);x.setAttribute('aria-pressed',String(i-1===chosen))});document.querySelectorAll('.tree-books a').forEach(a=>{a.hidden=!shown.some(b=>b.id===a.dataset.id)});document.querySelectorAll('#tree details').forEach(d=>{d.hidden=![...d.querySelectorAll('a')].some(a=>!a.hidden);if(q)d.open=true})}
function route(){const p=new URLSearchParams(location.hash.slice(1));current=books.find(b=>b.id===p.get('book'));$('#home').hidden=!!current;$('#reader').hidden=!current;if(!current){document.title='书虫 · 双语阅读书房';return}closeMenu();entries=flatten(current);let i=Math.max(0,Math.min(entries.length-1,Number(p.get('chapter'))||0));$('#bookTitle').textContent=current.title;document.title=current.title+' · 书虫双语书房';$('#breadcrumb').textContent=levels[current.level].label+' / '+current.title;$('#chapters').replaceChildren();entries.forEach((n,j)=>{let o=new Option((j===0?'封面 · ':'')+n.title,String(j));$('#chapters').add(o)});$('#chapters').value=i;$('#prev').disabled=i===0;$('#next').disabled=i===entries.length-1;$('#readStatus').textContent='正在打开：'+entries[i].title;$('#page').src=entries[i].href;writeStore('bookworms-last',location.hash);$('#resume').href=location.hash;$('#resume').hidden=false;document.querySelectorAll('.tree-books a').forEach(a=>{a.classList.toggle('active',a.dataset.id===current.id);if(a.dataset.id===current.id)a.closest('details').open=true})}
function go(i){location.hash='book='+current.id+'&chapter='+i}
$('#chapters').onchange=e=>go(e.target.value);$('#prev').onclick=()=>go(Number($('#chapters').value)-1);$('#next').onclick=()=>go(Number($('#chapters').value)+1);
function size(){let d=$('#page').contentDocument;if(d?.body)d.body.style.setProperty('font-size',font+'px','important')}
$('#larger').onclick=()=>{font=Math.min(32,font+2);size()};$('#smaller').onclick=()=>{font=Math.max(14,font-2);size()};
$('#page').onload=()=>{let d=$('#page').contentDocument;if(!current||!d)return;size();$('#readStatus').textContent='已打开 · '+(d.title||current.title);d.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;const u=new URL(a.getAttribute('href'),d.URL);const base=new URL('content/',location.href);if(u.origin!==base.origin||!u.pathname.startsWith(base.pathname)){e.preventDefault();return}let i=entries.findIndex(x=>new URL(x.href,location.href).href===u.href);if(i>=0){e.preventDefault();go(i)}})};
$('#search').oninput=()=>{if(current)location.hash='';draw()};window.onhashchange=route;
fetch('catalog.json').then(r=>{if(!r.ok)throw Error('目录加载失败');return r.json()}).then(data=>{levels=data;books=levels.flatMap(l=>l.children);[-1,...levels.keys()].forEach(i=>{const b=document.createElement('button');b.textContent=i<0?'全部':levels[i].label;b.onclick=()=>{chosen=i;draw()};$('#filters').append(b)});levels.forEach(l=>{const d=document.createElement('details'),s=document.createElement('summary'),list=document.createElement('div');s.textContent=l.label+' · '+l.children.length+' 本';list.className='tree-books';l.children.forEach(b=>{const a=document.createElement('a');a.href='#book='+b.id;a.dataset.id=b.id;a.textContent=b.title;list.append(a)});d.append(s,list);$('#tree').append(d)});const last=readStore('bookworms-last');if(last&&/^#book=\d-\d+/.test(last)){$('#resume').href=last;$('#resume').hidden=false}draw();route()}).catch(e=>{$('#count').textContent='加载失败，请刷新重试';console.error(e)});
