// Small, explicit learning patterns. These are reading hints, not a full parser.
window.StudyRules={
 phrases:[
  ['true to form',/\btrue to form\b/i,'一如既往；果然不出所料'],
  ['be dying to do',/\b(?:am|is|are|was|were|be) dying to\b/i,'非常想做某事；迫不及待地想……'],
  ['show off',/\bshow(?:s|ed|ing)? off\b/i,'炫耀；卖弄；展示'],
  ['hang around',/\b(?:hang(?:s|ing)?|hung) around\b/i,'闲待着；在附近逗留'],
  ['as it turns out',/\bas it turn(?:s|ed)? out\b/i,'结果是；后来发现'],
  ['make friends with',/\b(?:make|makes|making|made) friends with\b/i,'与……交朋友'],
  ['kick around',/\bkick(?:s|ed|ing)? around\b/i,'踢来踢去；也可指粗暴对待、欺负，需结合语境'],
  ['dead meat',/\bdead meat\b/i,'口语：要倒霉的人；麻烦大了'],
  ['look up',/\blook(?:s|ed|ing)? up\b/i,'抬头看；查阅（根据宾语判断）'],
  ['get off',/\b(?:get|gets|getting|got) off\b/i,'下来；离开；下车（结合上下文）'],
  ['go out',/\b(?:go|goes|going|went|gone) out\b/i,'出去；外出；也可指灯火熄灭'],
  ['turn out',/\bturn(?:s|ed|ing)? out\b/i,'结果是；原来是；出席（结合上下文）'],
  ['at the time',/\bat the time\b/i,'当时'],
  ['as soon as',/\bas soon as\b/i,'一……就……'],
  ['in spite of',/\bin spite of\b/i,'尽管；后面通常接名词或动名词'],
  ['instead of',/\binstead of\b/i,'代替；而不是'],
  ['used to do',/\bused to (?!the\b|it\b|being\b)[a-z]+\b/i,'可表示过去常常；注意与 be/get used to（习惯于）区分'],
  ['be used to',/\b(?:am|is|are|was|were|be|been|get|got) used to\b/i,'习惯于；通常接名词或动名词；若后接动词原形也可能表示“被用来”'],
  ['a great deal',/\ba (?:great|good) deal\b/i,'许多；大量'],
  ['all of a sudden',/\ball of a sudden\b/i,'突然'],
  ['in front of',/\bin front of\b/i,'在……前面'],
  ['take care of',/\b(?:take|takes|taking|took|taken) care of\b/i,'照顾；照料；处理'],
  ['look forward to',/\blook(?:s|ed|ing)? forward to\b/i,'期待；后接名词或动名词'],
  ['give up',/\b(?:give|gives|giving|gave|given) up\b/i,'放弃；停止'],
  ['find out',/\b(?:find|finds|finding|found) out\b/i,'查明；发现；弄清'],
  ['put up with',/\bput(?:s|ting)? up with\b/i,'忍受；容忍'],
  ['come across',/\b(?:come|comes|coming|came) across\b/i,'偶然遇见或发现'],
  ['take place',/\b(?:take|takes|taking|took|taken) place\b/i,'发生；举行'],
  ['set off',/\bset(?:s|ting)? off\b/i,'出发；引发；使……响起'],
  ['at last',/\bat last\b/i,'终于；最终'],
  ['as if',/\bas if\b/i,'好像；仿佛'],
  ['as though',/\bas though\b/i,'好像；仿佛'],
  ['no longer',/\bno longer\b/i,'不再'],
  ['on purpose',/\bon purpose\b/i,'故意地'],
  ['in a hurry',/\bin a hurry\b/i,'匆忙；急于'],
  ['by the way',/\bby the way\b/i,'顺便说一下'],
  ['at once',/\bat once\b/i,'立刻；同时（结合上下文）'],
  ['after all',/\bafter all\b/i,'毕竟；终究'],
  ['not at all',/\bnot at all\b/i,'一点也不；不客气'],
  ['as well as',/\bas well as\b/i,'以及；也；和……一样好（结合结构判断）'],
  ['out of sight',/\bout of sight\b/i,'看不见；在视野之外'],
  ['make up one’s mind',/\b(?:make|made|making) up (?:my|your|his|her|our|their) mind\b/i,'下定决心'],
  ['keep an eye on',/\b(?:keep|kept|keeping) an eye on\b/i,'留意；照看'],
  ['so far',/\bso far\b/i,'到目前为止；这么远'],
  ['for a while',/\bfor a while\b/i,'一会儿；一段时间'],
  ['in order to',/\bin order to\b/i,'为了；后接动词原形'],
  ['be about to',/\b(?:am|is|are|was|were|be) about to\b/i,'正要；即将'],
  ['get along with',/\b(?:get|gets|getting|got) along with\b/i,'与……相处；进展'],
  ['take a look',/\b(?:take|takes|taking|took) a look\b/i,'看一看'],
  ['of course',/\bof course\b/i,'当然'],
 ],
 grammar:[
  ['否定过去时：did not + 动词原形',/\bdid(?: not|n't)\s+[a-z]+\b/i,'did 承担过去时，后面的实义动词用原形。didn’t 是 did not 的缩写。'],
  ['过去进行时：was/were + -ing',/\b(?:was|were)\s+(?:not\s+)?(?:\w+ly\s+)?[a-z]+ing\b/i,'常用于交代过去某时正在进行的动作或背景；像 was dying to 也可能是固定表达。'],
  ['过去完成时：had + 过去分词',/\bhad\s+(?:not\s+|never\s+|already\s+)?(?:been|seen|done|gone|come|taken|given|made|left|found|known|heard|told|become|written|forgotten|begun|[a-z]+ed)\b/i,'通常表示在另一个过去动作之前已经发生的事，即“过去的过去”。'],
  ['现在完成时：have/has + 过去分词',/\b(?:have|has)\s+(?:not\s+|never\s+|already\s+)?(?:been|seen|done|gone|come|taken|given|made|left|found|known|heard|told|written|[a-z]+ed)\b/i,'把过去的动作与现在联系起来；可能强调结果、经历或持续到现在。'],
  ['不定式中的被动结构',/\bto be\s+(?:[a-z]+ed|seen|told|given|taken|known|heard|left|made)\b/i,'to be + 过去分词常表示“被……”。例如 to be kicked around 可理解为“被踢来踢去／被欺负”。'],
  ['原因从句：because',/\bbecause\s+(?!of\b)[a-z]/i,'because 后接说明原因的从句；注意 because of 后通常接名词或动名词，而不是完整从句。'],
  ['让步从句：although / though',/\b(?:although|though)\s+[a-z]/i,'表示“虽然／尽管”，从句与主句之间通常存在转折或反差。'],
  ['时间从句：the minute + 句子',/\bthe minute\s+(?:I|you|he|she|we|they|it)\b/i,'the minute 在这里相当于 as soon as，表示“一……就……”，不一定指实际的一分钟。'],
  ['建议句型：Why don’t you…?',/\bwhy don(?:'|’)t you\b/i,'常用来提建议，可译为“你为什么不……呢／不如……”。后接动词原形。'],
  ['enough … to do',/\benough\b[^.!?]{0,80}\bto\s+[a-z]+/i,'表示具备足够的程度或条件去做某事；enough 可修饰名词，也可放在形容词或副词之后。'],
  ['be busy doing',/\b(?:am|is|are|was|were|be|wasn't|weren't)\s+busy\s+[a-z]+ing\b/i,'表示“忙于做某事”，busy 后直接接动名词，一般不写成 busy to do。'],
  ['neither of + 复数对象',/\bneither of\b/i,'表示“两者都不”；与 either of（两者中的任意一个）区分。'],
  ['间接疑问：疑问词 + 陈述语序',/\b(?:know|knew|wonder|wondered|understand|understood|asked)\b[^.!?]{0,60}\b(?:why|how|where|whether|what)\b/i,'疑问内容嵌入另一个句子时，通常使用陈述语序，而不是直接问句的倒装语序。'],
  ['条件从句：If…',/^(?:[“"']\s*)?if\s+/i,'if 从句提出条件，主句说明相应结果；具体时态需结合原句判断，不能仅凭 if 就判定为虚拟语气。'],
  ['比较结构：as … as',/\bas\s+[a-z]+(?:\s+[a-z]+)?\s+as\b/i,'常用于同级比较，表示“和……一样……”。注意 as soon as 等固定连接表达另有含义。'],
  ['so … that …',/\bso\s+[a-z]+(?:\s+[a-z]+){0,3}\s+that\b/i,'可能表示“如此……以至于……”。若 so that 连在一起，则常表示目的或结果，要结合原句区分。'],
  ['情态动词 + 动词原形',/\b(?:could|would|should|must|might|cannot|couldn't|wouldn't|shouldn't)\s+(?!have\b)[a-z]+\b/i,'情态动词后通常用动词原形，用来表达能力、可能性、意愿或义务；具体含义依语境而定。'],
 ]
};
